FROM --platform=linux/amd64 node:alpine
WORKDIR /app
COPY index.html server.js /app/
COPY images/ /app/images/
ENV PORT=80
ENV BUGS_DIR=/data/bugs
VOLUME /data/bugs
EXPOSE 80
CMD ["node", "server.js"]
